INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (1, '2023-05-25 09:16:31', '2023-05-26 03:41:23', 1, 0, '[]', '-home', 'home/index', '/home', 1, 12, '首页', 'iconfont icon-shouye', 0, 1, 1, 0, '', 0, 'test,test');
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (2, '2023-05-25 09:16:31', '2023-05-25 14:27:22', 1, 0, '[]', 'system', 'layout/routerView/parent', '/system', 1, 0, '系统设置', 'iconfont icon-xitongshezhi', 0, 1, 0, 0, '', 0, null);
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (3, '2023-05-25 09:16:31', '2023-05-28 13:45:56', 3, 2, '[2]', '-system-menu', 'system/menu/index', '/system/menu', 1, 0, '菜单管理', 'iconfont icon-caidan', 0, 1, 0, 0, '', 0, null);
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (4, '2023-05-25 09:16:31', '2023-05-28 13:46:03', 5, 2, '[2]', '-system-user', 'system/user/index', '/system/user', 1, 0, '用户管理', 'iconfont icon-icon-', 0, 1, 0, 0, '', 0, 'user_page;role_page');
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (5, '2023-05-25 09:16:31', '2023-05-28 13:46:09', 3, 2, '[2]', '-system-role', 'system/role/index', '/system/role', 1, 0, '角色管理', 'ele-ColdDrink', 0, 1, 0, 0, null, 0, null);
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (6, '2023-05-27 12:14:12', '2023-05-27 12:14:12', 0, 21, '[2, 21]', '', '', '', 0, 0, '增加员工', '', 0, 1, 0, null, '', 0, 'user_create');
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (7, '2023-05-27 16:06:05', '2023-05-28 13:46:20', 4, 2, '[2]', '-system-dic', '/system/dic/index', '/system/dic', 1, 10, '字典', 'iconfont icon-yangan', 0, 1, 0, null, '', 0, '');
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (8, '2023-05-30 15:21:34', '2023-05-30 15:27:32', 4, 2, '[2]', '-system-login-log-index', '/system/login-log/index', '/system/login-log/index', 1, 0, '登录日志', 'iconfont icon-icon-', 0, 1, 0, 0, '', 0, '');
INSERT INTO evoltb_identity_permission (id_, create_at_, update_at_, version_, parent_id_, parent_ids_, name_, component_, path_, type_, sort_, title_, icon_, is_hide_, is_keep_alive_, is_affix_, is_link_, link_, is_iframe_, perm_) VALUES (9, '2023-05-30 15:39:45', '2023-05-30 15:39:45', 0, 2, '[2]', '-system-operation-log-index', '/system/operation-log/index', '/system/operation-log/index', 1, 0, '操作日志', 'iconfont icon-quanxian', 0, 1, 0, null, '', 0, '');
