server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 300
      min-spare: 10
    # 超出这个拒绝
    accept-count: 100
    connection-timeout: 30000
    max-connections: 8192
  port: 8081




logging:
  # 日志名称
  filename: app

evolpn:
  pay:
    notify-domain: http://locahost:8081
    now_payments_api_key: 213C3GW-DP54P9F-JDAWWXW-3Q51RQN
    now-payments-ipn-secret:
  snowflake-host: 2