server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 300
      min-spare: 10
    # 超出这个拒绝
    accept-count: 100
    connection-timeout: 30000
    max-connections: 8192
  port: 8081


rocketmq:
  name-server: 192.168.0.251:9876
  producer:
    group: producer-group-test
    topic: topic-test


evolpn:
  snowflake-host: 1

logging:
  # 日志名称
  filename: app